language: python

python:
  - 3.8
  - 3.9
  - 3.10
  - 3.11
  - 3.12

env:
  - DJANGO="Django>=4.2,<4.3"
  - DJANGO="Django>=5.0,<5.1"
  - DJANGO="Django>=5.1,<5.2"

install:
  - pip install coverage coveralls $DJANGO

script: coverage run -a --branch setup.py test

matrix:
  exclude:
    - python: 3.8
      env: DJANGO="Django>=5.0,<5.1"
      env: DJANGO="Django>=5.1,<4.2"


after_success: coveralls
