language: python

python:
  - 3.7
  - 3.8
  - 3.9
  - 3.10
  - 3.11

env:
  - DJANGO="Django>=2.2,<2.3"
  - DJANGO="Django>=3.0,<3.1"
  - DJANGO="Django>=3.2,<3.3"

install:
  - pip install coverage coveralls $DJANGO

script: coverage run -a --branch setup.py test

matrix:
  exclude:
    - python: 3.7
      env: DJANGO="Django>=4.0,<4.1"

after_success: coveralls
